{
    "name": "US GAAP Workspace",
    "version": "19.0.1.3.3",
    "category": "Poseidon/SaaS",
    "summary": "The single installable Meridian US GAAP app: pulls the entire workspace suite",
    "description": (
        "Umbrella application for a Meridian US GAAP workspace. Customers "
        "install exactly one app; every suite module arrives as a dependency. "
        "The depends list is generated from the USGAAP family contract via "
        "backend/profiles/usgaap/profile.json. Edit "
        "backend/addons/family-contracts.json, regenerate profiles, then run "
        "infra/scripts/sync-usgaap-app.py --write. Never hand-edit depends here."
    ),
    "author": "Kodoo",
    "license": "LGPL-3",
    "depends": [
        "account_fleet",
        "accountant",
        "accounting_close",
        "accounting_pdf_reports",
        "app_common",
        "atheneum_saas",
        "document_knowledge",
        "document_page",
        "document_page_access_group",
        "fleet",
        "hr",
        "hr_attendance",
        "hr_course",
        "hr_department_code",
        "hr_employee_calendar_planning",
        "hr_employee_firstname",
        "hr_employee_language",
        "hr_employee_medical_examination",
        "hr_employee_second_lastname",
        "hr_expense",
        "hr_fleet",
        "hr_holidays",
        "hr_org_chart",
        "hr_recruitment",
        "hr_skills",
        "hr_timesheet",
        "im_livechat_kanban_fallback",
        "industry_real_estate",
        "knowledge",
        "knowledge_ai_bridge",
        "knowledge_checklist",
        "knowledge_content_format",
        "knowledge_document_link",
        "knowledge_dossier",
        "knowledge_import_export",
        "knowledge_page_publish",
        "knowledge_print",
        "knowledge_scriptorium",
        "knowledge_secret",
        "knowledge_suite",
        "knowledge_templates",
        "knowledge_todo_context",
        "knowledge_wikipedia",
        "kodoo_ai_center",
        "kodoo_checklist",
        "kodoo_claw",
        "kodoo_forge",
        "kodoo_forge_runtime",
        "kodoo_knowledge",
        "kodoo_legal",
        "kodoo_mail_gateway",
        "kodoo_mcp",
        "kodoo_mcp_clickup",
        "kodoo_secure_inbox",
        "kodoo_studio",
        "kodoo_studio_integration",
        "kodoo_telemetry",
        "kodoo_web_clipboard_fix",
        "l10n_us",
        "l10n_us_account",
        "lunch",
        "maintenance",
        "meridian_onboarding",
        "meridian_saas",
        "om_account_accountant",
        "om_account_asset",
        "om_account_budget",
        "om_account_daily_reports",
        "om_account_followup",
        "om_fiscal_year",
        "om_recurring_payments",
        "poseidon_accounting_kernel",
        "poseidon_books_agent",
        "poseidon_budget",
        "poseidon_company_group",
        "poseidon_cost_center",
        "poseidon_knowledge",
        "poseidon_mapping_governance",
        "poseidon_mcp",
        "poseidon_reconciliation",
        "poseidon_us_tax",
        "project",
        "project_todo",
        "purchase",
        "qbo_bridge",
        "qbo_bridge_standard_chart",
        "survey",
        "synconics_bi_dashboard",
        "web_mobile",
        "website_configurator_action_fix"
    ],
    "data": [
        "security/meridian_operational_roles.xml",
        "data/kodoo_mcp_accounting_seed.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
